export const experiencesEn = [
    {
        title: "Fullstack Engineer",
        company: 'Fenix Capital Funding',
        period: "Apr 2024 - Present",
        technologies: 'Python, Django, TailwindCSS, Docker, SQL Server',
        missions: [
            "Developed an Enterprise Resource Planning (ERP) System entirely from the ground up using Django.",
            "Containerized the application within Docker for optimal scalability and deployment efficiency.",
            "The system relies on a SQL Server as a robust relational database.",
            "Used Nginx serving as a key component for traffic management.",
        ],
        detailIsDisplayed: false,
        image: 'assets/images/fenix_capital_funding_logo.webp',
    },
    {
        title: "Fullstack Engineer",
        company: 'Freelance',
        period: "Aug 2023 - Feb 2024 (7 months)",
        technologies: 'Python, Django, TailwindCSS, Docker',
        missions: [
            "Developed and maintained web applications for various clients.",
            "Collaborated with cross-functional teams to define project requirements and deliverables.",
            "Implemented new features and optimized existing functionalities.",
        ],
        detailIsDisplayed: false,
        image: '',
    },
    {
        title: "Business Application Engineer II",
        company: 'CDS, a Hewlett Packard Enterprise company',
        period: "Feb 2022 - Jul 2023 (1 year 6 months)",
        technologies: 'Python, SQL Server, Red Hat Linux Enterprise',
        missions: [
            "Created a series of ETLs using python with SQLAlchemy to extract and process data from different sources (Apis,AD,Files,etc...) and load them into a SQL Server database",
            "Optimized the scripts to run in multithreading and thus improve their performance",
            "Written unit tests for the ETLs using pytest",
            "Designed and created different optimized tables and views in SQL Server to store data from the ETLs",
            "Optimized the tables and views by creating indexes and using partitioning to improve the performance of the queries",
            "Created triggers and stored procedures in SQL Server to automate some tasks",
            "Deployed the ETLs in a Red Hat Linux Enterprise server using cron jobs to run them periodically",
            "Integrated the ETLs data with a PowerBi dashboard to display the data in a user friendly way",
            "Installed all of the dependencies needed for the ETLs to run in the Red Hat Linux Enterprise server",
        ],
        detailIsDisplayed: false,
        image: 'assets/images/cds.webp',
    },
    {
        title: "Business Application Engineer",
        company: 'CDS, a Hewlett Packard Enterprise company',
        period: "Jun 2021 - Feb 2022 (9 months)",
        technologies: 'Python, SQL Server, Red Hat Linux Enterprise',
        missions: [
            "Created a series of ETLs using python with SQLAlchemy to extract and process data from different sources (Apis,AD,Files,etc...) and load them into a SQL Server database",
            "Optimized the scripts to run in multithreading and thus improve their performance",
            "Written unit tests for the ETLs using pytest",
            "Designed and created different optimized tables and views in SQL Server to store data from the ETLs",
            "Optimized the tables and views by creating indexes and using partitioning to improve the performance of the queries",
            "Deployed the ETLs in a Red Hat Linux Enterprise server using cron jobs to run them periodically",
            "Integrated the ETLs data with a PowerBi dashboard to display the data in a user friendly way",
            "Installed all of the dependencies needed for the ETLs to run in the Red Hat Linux Enterprise server",
        ],
        detailIsDisplayed: false,
        image: 'assets/images/cds.webp',
    },
    {
        title: "Internship",
        company: 'CDS, a Hewlett Packard Enterprise company',
        period: "Mar 2021 - May 2021 (3 months)",
        technologies: 'Microsoft PowerApps, PowerAutomate, PowerBi, SQL Server, Springboot, Kafka, MongoDB',
        missions: [
            "Created a PowerApps application to demo a computer's shop",
            "Created a PowerAutomate flow to send an email when a new computer is added to the database",
            "Integrated the PowerApps application with a MSSQL database",
            "Created a SSIS automation to load data from an Excel file to a MSSQL database",
            "Created a PowerBi dashboard to display millions of pre-generated data from people",
            "Created a Springboot application using microservices architecture with kafka and MongoDB for a file upload/download application",
        ],
        detailIsDisplayed: false,
        image: 'assets/images/cds.webp',
    },
];
