export const experiencesEs = [
    {
        title: "Fullstack Engineer",
        company: 'Fenix Capital Funding',
        period: "Abr 2024 - Present",
        technologies: 'Python, Django, TailwindCSS, Docker, SQL Server',
        missions: [
            "Desarrollado un sistema de planificación de recursos empresariales (ERP) desde cero utilizando Django.",
            "Contenedorizado la aplicación dentro de Docker para una escalabilidad óptima y eficiencia de despliegue.",
            "El sistema se basa en un SQL Server como base de datos relacional robusta.",
            "Utilizado Nginx como un componente clave para la gestión del tráfico.",
        ],
        detailIsDisplayed: false,
        image: 'assets/images/fenix_capital_funding_logo.webp',
    },
    {
        title: "Fullstack Engineer",
        company: 'Freelance',
        period: "Ago 2023 - Feb 2024 (7 months)",
        technologies: 'Python, Django, TailwindCSS, Docker',
        missions: [
            "Desarrollado y mantenido aplicaciones web para varios clientes.",
            "Colaborado con equipos multifuncionales para definir los requisitos y entregables del proyecto.",
            "Implementado nuevas funcionalidades y optimizado las existentes.",
        ],
        detailIsDisplayed: false,
        image: '',
    },
    {
        title: "Business Application Engineer II",
        company: 'CDS, a Hewlett Packard Enterprise company',
        period: "Feb 2022 - Jul 2023 (1 año 6 meses)",
        technologies: 'Python, SQL Server, Red Hat Linux Enterprise',
        missions: [
            "Creado una serie de ETLs usando python con SQLAlchemy para extraer y procesar datos de diferentes fuentes (Apis,AD,Files,etc...) y cargarlos en una base de datos SQL Server",
            "Optimizados los scripts para que corran en paralelo y así mejorar el rendimiento de los mismos",
            "Escrito pruebas unitarias para los ETLs usando pytest",
            "Diseñado y creado diferentes tablas y vistas optimizadas en SQL Server para almacenar datos de los ETLs",
            "Optimizado las tablas y vistas creando índices y usando particionamiento para mejorar el rendimiento de las consultas",
            "Creado triggers y stored procedures en SQL Server para automatizar algunas tareas",
            "Desplegado los ETLs en un servidor Red Hat Linux Enterprise usando cron jobs para ejecutarlos periódicamente",
            "Integrado los datos de los ETLs con un dashboard de PowerBi para mostrar los datos de una manera amigable",
            "Instalado todas las dependencias necesarias para que los ETLs corran en el servidor Red Hat Linux Enterprise",
        ],
        detailIsDisplayed: false,
        image: 'assets/images/cds.webp',
    },
    {
        title: "Business Application Engineer",
        company: 'CDS, a Hewlett Packard Enterprise company',
        period: "Jun 2021 - Feb 2022 (9 meses)",
        technologies: 'Python, SQL Server, Red Hat Linux Enterprise',
        missions: [
            "Creado una serie de ETLs usando python con SQLAlchemy para extraer y procesar datos de diferentes fuentes (Apis,AD,Files,etc...) y cargarlos en una base de datos SQL Server",
            "Optimizados los scripts para que corran en paralelo y así mejorar el rendimiento de los mismos",
            "Escrito pruebas unitarias para los ETLs usando pytest",
            "Diseñado y creado diferentes tablas y vistas optimizadas en SQL Server para almacenar datos de los ETLs",
            "Optimizado las tablas y vistas creando índices y usando particionamiento para mejorar el rendimiento de las consultas",
            "Desplegado los ETLs en un servidor Red Hat Linux Enterprise usando cron jobs para ejecutarlos periódicamente",
            "Integrado los datos de los ETLs con un dashboard de PowerBi para mostrar los datos de una manera amigable",
            "Instalado todas las dependencias necesarias para que los ETLs corran en el servidor Red Hat Linux Enterprise",
        ],
        detailIsDisplayed: false,
        image: 'assets/images/cds.webp',
    },
    {
        title: "Internship",
        company: 'CDS, a Hewlett Packard Enterprise company',
        period: "Mar 2021 - May 2021 (3 meses)",
        technologies: 'Microsoft PowerApps, PowerAutomate, PowerBi, SQL Server, Springboot, Kafka, MongoDB',
        missions: [
            "Creada una aplicación de PowerApps para una demo de una tienda de ordenadores",
            "Creado un flujo de PowerAutomate para enviar un email cuando un nuevo ordenador es añadido a la base de datos",
            "Integrado la aplicación de PowerApps con una base de datos MSSQL",
            "Creada una automatización con SSIS para cargar de forma masiva datos de un fichero Excel a una base de datos MSSQL",
            "Creado un dashboard de PowerBi para mostrar los datos de la base de datos",
            "Creada una aplicación de Springboot usando arquitectura de microservicios con kafka y MongoDB para una aplicación de subida/descarga de ficheros",
        ],
        detailIsDisplayed: false,
        image: 'assets/images/cds.webp',
    },
];
